#ifndef OBJECT_LINK_CHILD_H
#define OBJECT_LINK_CHILD_H 1

extern u64 gLinkChildEyesOpenTex[];
extern u64 gLinkChildEyesHalfTex[];
extern u64 gLinkChildEyesClosedfTex[];
extern u64 gLinkChildEyesLeftTex[];
extern u64 gLinkChildEyesRightTex[];
extern u64 gLinkChildEyesWideTex[];
extern u64 gLinkChildEyesDownTex[];
extern u64 gLinkChildEyesWincingTex[];
extern u64 gLinkChildMouthClosedTex[];
extern u64 gLinkChildMouthHalfTex[];
extern u64 gLinkChildMouthOpenTex[];
extern u64 gLinkChildMouthSmileTex[];
extern u64 gLinkChildNoseTex[];
extern u64 gLinkChildEarTex[];
extern u64 gLinkChildBeltTLUT[];
extern u64 gLinkChildSkinTLUT[];
extern u64 gLinkChildLowerBootTex[];
extern u64 gLinkChildUnusedBootTex[];
extern u64 gLinkChildBootTex[];
extern u64 gLinkChildWaistTex[];
extern u64 gLinkChildBeltTex[];
extern u64 gLinkChildBeltClaspTex[];
extern Vtx object_link_childVtx_006A80[];
extern Gfx gLinkChildLinkDekuStickDL[];
extern u64 gLinkChildFairyOcarinaTex[];
extern u64 gLinkChildGoronBraceletTex[];
extern u64 gLinkChildGoronSymbolTex[];
extern u64 gLinkChildDekuShieldBackTex[];
extern u64 gLinkChildDekuShieldFrontTex[];
extern u64 gLinkChildSlingshotTex[];
extern u64 gLinkChildSlingshotSeedTex[];
extern u64 gLinkChildHandTLUT[];
extern u64 gLinkChildSwordsTLUT[];
extern u64 gLinkChildSwordTLUT[];
extern u64 gLinkChildHandTex[];
extern u64 gLinkChildKokiriSwordSheathTex[];
extern u64 gLinkChildSwordJewelTex[];
extern u64 gLinkChildMasterSwordPommelTex[];
extern u64 gLinkChildMasterSwordGuardTex[];
extern u64 gLinkChildMasterSwordEmblemTex[];
extern Vtx object_link_childVtx_00ABF0[];
extern Gfx gLinkChildLeftHandNearDL[];
extern Gfx gLinkChildLeftFistNearDL[];
extern Gfx gLinkChildLeftFistAndKokiriSwordNearDL[];
extern Gfx gLinkChildRightHandNearDL[];
extern Gfx gLinkChildRightHandClosedNearDL[];
extern Gfx gLinkChildRightFistAndDekuShieldNearDL[];
extern Gfx gLinkChildLeftFistAndBoomerangNearDL[];
extern Gfx gLinkChildLeftHandHoldingMasterSwordDL[];
extern Gfx gLinkChildRightHandAndOotNearDL[];
extern Gfx gLinkChildRightHandHoldingFairyOcarinaNearDL[];
extern Gfx gLinkChildRightHandHoldingSlingshotNearDL[];
extern Gfx gLinkChildLeftHandUpNearDL[];
extern Gfx gLinkChildGoronBraceletDL[];
extern Gfx gLinkChildRightHandHoldingOOTFarDL[];
extern Gfx gLinkChildRightArmStretchedSlingshotDL[];
extern Gfx gLinkChildBottleDL[];
extern Vtx object_link_childVtx_01C978[];
extern Vtx object_link_childVtx_01EDA8[];
extern Vtx object_link_childVtx_01F528[];
extern Vtx object_link_childVtx_01FE08[];
extern Gfx gLinkChildWaistNearDL[];
extern Gfx gLinkChildRightThighNearDL[];
extern Gfx gLinkChildRightShinNearDL[];
extern Gfx gLinkChildRightFootNearDL[];
extern Gfx gLinkChildLeftThighNearDL[];
extern Gfx gLinkChildLeftShinNearDL[];
extern Gfx gLinkChildLeftFootNearDL[];
extern Gfx gLinkChildCollarNearDL[];
extern Gfx gLinkChildTorsoNearDL[];
extern Gfx gLinkChildHeadNearDL[];
extern Gfx gLinkChildHatNearDL[];
extern Gfx gLinkChildRightShoulderNearDL[];
extern Gfx gLinkChildRightForearmNearDL[];
extern Gfx gLinkChildLeftShoulderNearDL[];
extern Gfx gLinkChildLeftForearmNearDL[];
extern Vtx object_link_childVtx_022148[];
extern Gfx gLinkChildSlingshotStringDL[];
extern Vtx object_link_childVtx_022208[];
extern Gfx gLinkChildDekuShieldDL[];
extern Mtx gLinkChildDekuShieldMtx;
extern Gfx gLinkChildDekuShieldWithMatrixDL[];
extern u64 gLinkChildSpookyMaskTex[];
extern u64 gLinkChildKeatonMaskEyeBrowTex[];
extern u64 gLinkChildKeatonMaskEarTex[];
extern u64 gLinkChildSkullMaskEyeTex[];
extern u64 gLinkChildMaskOfTruthTex[];
extern u64 gLinkChildMaskOfTruthCurveTex[];
extern u64 gLinkChildGoronMaskMouthTex[];
extern u64 gLinkChildGoronMaskEyeTex[];
extern u64 gLinkChildGoronMaskNoseTex[];
extern u64 gLinkChildGoronMaskHairTex[];
extern u64 gLinkChildSkullMaskTeethTex[];
extern u64 gLinkChildGoronMaskEarTex[];
extern u64 gLinkChildZoraMaskEyeBoarderTex[];
extern u64 gLinkChildZoraMaskEarTex[];
extern u64 gLinkChildSkullMaskNoseTex[];
extern u64 gLinkChildZoraMaskEyeTex[];
extern u64 gLinkChildZoraMaskMouthTex[];
extern u64 gLinkChildGerudoMaskEyeTex[];
extern u64 gLinkChildGerudoMaskMouthTex[];
extern u64 gLinkChildGerudoMaskHairTex[];
extern u64 gLinkChildGerudoMaskNoseTex[];
extern Vtx object_link_childVtx_029220[];
extern Gfx gLinkChildSkullMaskDL[];
extern Gfx gLinkChildSpookyMaskDL[];
extern Gfx gLinkChildKeatonMaskDL[];
extern Gfx gLinkChildMaskOfTruthDL[];
extern Gfx gLinkChildGoronMaskDL[];
extern Gfx gLinkChildZoraMaskDL[];
extern Gfx gLinkChildGerudoMaskDL[];
extern u64 gLinkChildBunnyHoodEyeTex[];
extern u64 gLinkChildBunnyHoodTex[];
extern u64 gLinkChildBunnyHoodEarTex[];
extern Vtx object_link_childVtx_02C428[];
extern Gfx gLinkChildBunnyHoodDL[];
extern LodLimb gLinkChildRootLimb;
extern LodLimb gLinkChildWaistLimb;
extern LodLimb gLinkChildLowerControlLimb;
extern LodLimb gLinkChildRightThighLimb;
extern LodLimb gLinkChildRightShinLimb;
extern LodLimb gLinkChildRightFootLimb;
extern LodLimb gLinkChildLeftThighLimb;
extern LodLimb gLinkChildLeftShinLimb;
extern LodLimb gLinkChildLeftFootLimb;
extern LodLimb gLinkChildUpperControlLimb;
extern LodLimb gLinkChildHeadLimb;
extern LodLimb gLinkChildHatLimb;
extern LodLimb gLinkChildCollarLimb;
extern LodLimb gLinkChildLeftshoulderLimb;
extern LodLimb gLinkChildLeftForearmLimb;
extern LodLimb gLinkChildLeftHandLimb;
extern LodLimb gLinkChildRightshoulderLimb;
extern LodLimb gLinkChildRightForearmLimb;
extern LodLimb gLinkChildRightHandLimb;
extern LodLimb gLinkChildTorsoLimb;
extern void* gLinkChildSkelLimbs[];
extern FlexSkeletonHeader gLinkChildSkel;



// Global
extern u64 gSwordBowHookshotHandTLUT[];
extern Gfx gLinkChildShieldRightFistDL[];

// Kokiri Sword
extern Vtx kokiri_sword_mm_blade_vtx[];
extern Gfx gLinkChildLeftHandHoldingBrokenSwordDL[];
extern Gfx gKokiriSwordBladeDL[];
extern Gfx gKokiriSwordHandleDL[];

// Razor Sword
extern u64 gRazorSwordHandleDesignTex[];
extern u64 gRazorSwordHandleGripTex[];
extern u64 gSwordMetalTex[];
extern Vtx razor_sword_handle_vtx[];
extern Vtx razor_sword_blade_vtx[];
extern Gfx gLinkChildLeftHandHoldingRazorSwordDL[];
extern Gfx gRazorSwordHandleDL[];
extern Gfx gRazorSwordBladeDL[];

// Gilded Sword
extern u64 object_link_child_Tex_01C380[];
extern u64 object_link_child_Tex_01C400[];
extern u64 object_link_child_Tex_01C900[];
extern u64 object_link_child_Tex_01D340[];
extern Vtx gilded_sword_handle_vtx[];
extern Vtx gilded_sword_blade_vtx[];
extern Gfx gLinkChildLeftHandHoldingSilverSwordDL[];
extern Gfx gLinkChildLeftHandHoldingGoldenSwordDL[];
extern Gfx gGildedSwordHandleDL[];
extern Gfx gSilverSwordBladeDL[];
extern Gfx gGoldenSwordBladeDL[];
extern Gfx gGildedSwordBladeDL[];

// Sheaths
extern Vtx razor_sword_sheath_vtx[];
extern Vtx gilded_sword_sheath_vtx[];
extern Mtx gSheathedRazorSwordMtx;
extern Mtx gSheathedGildedSwordMtx;
extern Gfx gSheathEmptyDL[];
extern Gfx gSheathedKokiriSwordDL[];
extern Gfx gSheathedRazorSwordDL[];
extern Gfx gSheathedGildedSwordDL[];
extern Gfx gKokiriSwordSheathDL[];
extern Gfx gRazorSwordSheathDL[];
extern Gfx gGildedSwordSheathDL[];

// Shields With Sheathed Swords
extern Gfx gLinkChildDekuShieldKokiriSwordSheathedDL[];
extern Gfx gLinkChildDekuShieldRazorSwordSheathedDL[];
extern Gfx gLinkChildDekuShieldGildedSwordSheathedDL[];
extern Gfx gLinkChildHerosShieldKokiriSwordSheathedDL[];
extern Gfx gLinkChildHerosShieldRazorSwordSheathedDL[];
extern Gfx gLinkChildHerosShieldGildedSwordSheathedDL[];
extern Gfx gLinkChildMirrorShieldKokiriSwordSheathedDL[];
extern Gfx gLinkChildMirrorShieldRazorSwordSheathedDL[];
extern Gfx gLinkChildMirrorShieldGildedSwordSheathedDL[];

// Shields With Sheaths
extern Gfx gLinkChildDekuShieldKokiriSwordSheathDL[];
extern Gfx gLinkChildDekuShieldRazorSwordSheathDL[];
extern Gfx gLinkChildDekuShieldGildedSwordSheathDL[];
extern Gfx gLinkChildHerosShieldKokiriSwordSheathDL[];
extern Gfx gLinkChildHerosShieldRazorSwordSheathDL[];
extern Gfx gLinkChildHerosShieldGildedSwordSheathDL[];
extern Gfx gLinkChildMirrorShieldKokiriSwordSheathDL[];
extern Gfx gLinkChildMirrorShieldRazorSwordSheathDL[];
extern Gfx gLinkChildMirrorShieldGildedSwordSheathDL[];

// Hero's Shield
extern u64 gLinkChildHerosShieldFrontTLUT[];
extern u64 gLinkChildHerosShieldBackTLUT[];
extern u64 gLinkChildHerosShieldFrontUpperTex[];
extern u64 gLinkChildHerosShieldFrontLowerTex[];
extern u64 gLinkChildHerosShieldBackTex[];
extern u64 gLinkChildShieldHandleTLUT[];
extern u64 gLinkChildShieldHandleTex[];
extern Vtx heros_shield_vtx[];
extern Mtx gLinkChildHerosShieldMtx;
extern Gfx gLinkChildHerosShieldDL[];
extern Gfx gLinkChildHerosShieldWithMtxDL[];

// Mirror Shield
extern u64 object_link_child_Tex_01C800[];
extern u64 object_link_child_Tex_01CB00[];
extern u64 object_link_child_Tex_01D300[];
extern u64 object_link_child_Tex_01D440[];
extern Vtx mirror_shield_vtx[];
extern Mtx gLinkChildMirrorShieldMtx;
extern Gfx gLinkChildMirrorShieldDL[];
extern Gfx gLinkChildMirrorShieldWithMtxDL[];

// Megaton Hammer
extern Vtx hammer_vtx[];
extern Gfx gLinkChildLeftHandHoldingHammerNearDL[];

// Hookshot
extern u64 gLinkChildHookshotHandleTex[];
extern u64 gLinkChildHookshotChainTex[];
extern u64 gLinkChildHookshotReticleTex[];
extern u64 gLinkChildHookshotHandTex[];
extern Vtx hookshot_chain_vtx[];
extern Vtx hookshot_reticle_vtx[];
extern Vtx hookshot_hand_vtx[];
extern Vtx hookshot_far_vtx[];
extern Vtx hookshot_tip_vtx[];
extern Gfx gLinkChildRightHandHoldingHookshot[];
extern Gfx gLinkChildRightHandHoldingHookshotNear[];
extern Gfx gLinkChildRightHandHoldingHookshotNearDL[];
extern Gfx gLinkChildRightHandHoldingHookshotFarDL[];
extern Gfx gLinkChildHookshotTipDL[];
extern Gfx gLinkChildHookshotChainDL[];
extern Gfx gLinkChildHookshotReticleDL[];

// Bow
extern u64 gLinkChildBowBodyTex[];
extern u64 gLinkChildBowTex[];
extern u64 gLinkChildBowDesignTex[];
extern Vtx heros_bow_vtx[];
extern Vtx heros_bow_string_vtx[];
extern Vtx heros_bow_first_person_vtx[];
extern Gfx gLinkChildRightHandHoldingBowNearDL[];
extern Gfx gLinkChildRightHandHoldingBowFirstPersonDL[];
extern Gfx gLinkChildBowStringDL[];

#endif
